# Generated by Django 4.2.2 on 2023-06-19 08:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="followings",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="followers",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
