# Generated by Django 4.2.2 on 2023-06-12 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_remove_user_nickname_user_gender_alter_user_age_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="age",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="gender",
            field=models.CharField(
                choices=[("male", "Male"), ("female", "Female")],
                max_length=10,
                null=True,
            ),
        ),
    ]
