# Generated by Django 4.2.2 on 2023-06-20 03:29

from django.db import migrations, models
import users.validators


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_user_followings"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="password",
            field=models.CharField(
                max_length=256, validators=[users.validators.validate_password]
            ),
        ),
    ]
