# Generated by Django 4.2.2 on 2023-06-20 12:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("articles", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="like",
            field=models.ManyToManyField(
                blank=True, related_name="articles", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
