# Generated by Django 4.2.2 on 2023-06-14 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngredientLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(blank=True, null=True)),
                ('link_img', models.URLField(blank=True, null=True)),
                ('Ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.ingredient')),
            ],
        ),
    ]
