# Generated by Django 4.2.2 on 2023-06-21 11:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("articles", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="like",
            field=models.ManyToManyField(
                blank=True, related_name="likes", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.DeleteModel(
            name="Likes",
        ),
    ]
