# Generated by Django 4.2.2 on 2023-06-18 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("articles", "0003_alter_comment_author"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ingredient",
            name="ingredient_info",
            field=models.TextField(default=list, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="ingredient",
            name="ingredient_name",
            field=models.ForeignKey(
                max_length=100,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="recipeingredients",
                to="articles.recipeingredient",
            ),
        ),
        migrations.AlterField(
            model_name="recipeingredient",
            name="ingredient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ingredients",
                to="articles.ingredient",
            ),
        ),
        migrations.AlterField(
            model_name="recipeingredient",
            name="ingredient_quantity",
            field=models.IntegerField(default=list),
        ),
        migrations.AlterField(
            model_name="recipeingredient",
            name="ingredient_unit",
            field=models.CharField(default=list, max_length=100),
        ),
    ]
