# Generated by Django 4.2.2 on 2023-06-15 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_ingredientlink'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredientlink',
            old_name='Ingredient',
            new_name='ingredient',
        ),
    ]
