# Generated by Django 4.2.2 on 2023-06-22 11:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("articles", "0003_alter_category_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="recipe",
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
