# Generated by Django 4.2.2 on 2023-07-02 22:56

import articles.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_alter_ingredient_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeingredient',
            name='ingredient_quantity',
            field=models.FloatField(default=list, validators=[articles.validators.validate_gt0]),
        ),
    ]
