# Generated by Django 4.2.2 on 2023-06-27 01:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("articles", "0004_alter_article_recipe"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="recomment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="recomments",
                to="articles.comment",
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="recipe",
            field=models.TextField(blank=True, null=True),
        ),
    ]
