# Generated by Django 4.2.2 on 2023-06-16 06:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_rename_ingredient_ingredientlink_ingredient'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
