# Generated by Django 4.2.2 on 2023-06-25 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0004_alter_article_recipe"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="recipe",
            field=models.TextField(blank=True, null=True),
        ),
    ]
