# Generated by Django 4.2.2 on 2023-06-19 00:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("articles", "0004_alter_ingredient_ingredient_info_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ingredient",
            name="id",
        ),
        migrations.AlterField(
            model_name="ingredient",
            name="ingredient_name",
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
