# Generated by Django 4.2.2 on 2023-07-04 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0004_alter_recipeingredient_ingredient_quantity"),
    ]

    operations = [
        migrations.AddField(
            model_name="ingredientlink",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="ingredientlink",
            name="price",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="ingredientlink",
            name="link",
            field=models.URLField(blank=True, max_length=100000, null=True),
        ),
        migrations.AlterField(
            model_name="ingredientlink",
            name="link_img",
            field=models.URLField(blank=True, max_length=100000, null=True),
        ),
    ]
