# Generated by Django 4.2.2 on 2023-06-16 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_alter_ingredient_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='updated_at',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
