# Generated by Django 4.2.2 on 2023-06-23 15:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("ai_process", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="imageupload",
            name="id",
        ),
        migrations.AddField(
            model_name="imageupload",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                serialize=False,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="imageupload",
            name="image",
            field=models.ImageField(null=True, upload_to=""),
        ),
    ]
