# docker-compose.yml
services:
  web:
    container_name: cookai
    image: ltekean/docker-cookai
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .env:/app/.env
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword

volumes:
  postgres_data:
